#!/bin/sh
RED="\033[1;31m"
GREEN="\033[1;32m"
NC="\033[0m"
linter_exit_code=1
staged_files=$(git diff --cached --diff-filter=d --name-only | grep '.ts\|.tsx'$)
./node_modules/.bin/prettier $staged_files -w
./node_modules/.bin/eslint $staged_files --quiet
linter_exit_code=$?
git add -f $staged_files
if [ $linter_exit_code -ne 0 ]
then
  echo "${RED} Prettier & Linter errors has occured ${NC}"
  exit 1
else
  echo "${GREEN} Prettier & Linter did not find any errors ${NC}"
  exit 0
fi
